# Generated by Django 4.2.2 on 2023-06-27 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("found", "Fundacja"),
                            ("ngo", "Organizacja pozarządowa"),
                            ("loccol", "Zbiórka lokalna"),
                        ],
                        default="found",
                    ),
                ),
                ("categories", models.ManyToManyField(to="charity.category")),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.SmallIntegerField()),
                ("address", models.CharField(max_length=64)),
                ("phone_number", models.IntegerField(max_length=9)),
                ("city", models.CharField(max_length=32)),
                ("zip_code", models.CharField(max_length=6)),
                ("pick_up_date", models.DateField()),
                ("pick_up_time", models.TimeField()),
                ("pick_up_comment", models.TextField()),
                ("categories", models.ManyToManyField(to="charity.category")),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charity.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
