# Generated by Django 4.2.2 on 2023-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="phone_number",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="donation",
            name="pick_up_comment",
            field=models.TextField(null=True),
        ),
    ]
