# Generated by Django 4.2.2 on 2023-06-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0002_alter_donation_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="is_taken",
            field=models.BooleanField(default=False),
        ),
    ]
